cmd.load("./S_000001.pdb")
print("Selecting first residue")
cmd.select("first_residue", "resi 1")
cmd.edit("first_residue and name C5'")
print("Adding O5' atom")
cmd.attach("O", 1, 2, "O5\'")
cmd.select("nucleic","resn A+C+G+T+U+DA+DC+DG+DT+DU")
cmd.alter("nucleic", "chain=''")
cmd.unpick()
cmd.deselect()
cmd.save("./dna.pdb")
